name: napari_movie
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - matplotlib
  - jupyter
  - ffmpeg
  - pip:
    - requests
    - napari
    - git+https://github.com/guiwitz/naparimovie.git@master#egg=naparimovie